### PR TITLE
Add Mineo (Docomo) APN settings

### PR DESCRIPTION
**Pull request by robin-reckmann**
I would like to add the APN settings of the Japanese MVNO Mineo.

Settings can be found here (only Japanese :-( ): https://support.mineo.jp/setup/guide/android_network.html

Mineo is offering plans for the three major Japanese providers (au, Docomo and Softbank). Their API settings differ in MCC, MNC and APN name. 
I am using the Docomo plan (MCC 440, MNC 10, APN mineo-d.jp) (see also here https://en.wikipedia.org/wiki/Mobile_Network_Codes_in_ITU_region_4xx_(Asia)#Japan_%E2%80%93_JP).

Confirmed to be working on comma three.

(I noticed that only the first entry in the list with matching MCC/MNC is used for connection. When I moved the Mineo entry below the next one in the list (bmobile), no LTE connection could be established, since only the connection to b-mobile was used. We might need a way to specify which APN to use(?))

### CODE REVIEW

**Comment by robbederks** [comment]
Instead of adding another provider, could you try just adding another APN section to the provider below it (it already has 2)? I think that might be the right way to do this.

**Comment by adeebshihadeh** [comment]
I updated serviceproviders.xml with what I think is the right way to add this MVNO. Can you test this?

**Comment by robin-reckmann** [comment]
Doesn't work unfortunately. 

Modem Manager is trying to connect using the first 44010 APN in the list (b-mobile):

Here the output of syslog:

```
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.546330] [modem0] user request to connect modem
Sep 30 00:47:15 tici ModemManager[4279]: <info>  [1632930435.551715] [modem0] simple connect started...
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.551799] [modem0]    PIN: unspecified
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.551840] [modem0]    operator ID: unspecified
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.551877] [modem0]    allowed roaming: no
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.551912] [modem0]    APN: dm.jplat.net
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.551951] [modem0]    IP family: ipv6
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.551987] [modem0]    allowed authentication: unspecified
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.552027] [modem0]    User: bmobile@u300
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.552065] [modem0]    Password: bmobile
Sep 30 00:47:15 tici ModemManager[4279]: <info>  [1632930435.552104] [modem0] simple connect state (4/8): wait to get fully enabled
Sep 30 00:47:15 tici ModemManager[4279]: <info>  [1632930435.552216] [modem0] simple connect state (5/8): register
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.552294] [modem0] already registered automatically in network '44010', automatic registration not launched...
Sep 30 00:47:15 tici ModemManager[4279]: <info>  [1632930435.552369] [modem0] simple connect state (6/8): bearer
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.552417] [modem0] creating new bearer...
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.553662] [modem0] deleted disconnected bearer at '/org/freedesktop/ModemManager1/Bearer/44'
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.553718] [modem0/bearer44] removing from bus
Sep 30 00:47:15 tici ModemManager[4279]: <info>  [1632930435.554734] [modem0] simple connect state (7/8): connect
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.554953] [modem0/bearer45] connecting...
Sep 30 00:47:15 tici ModemManager[4279]: <info>  [1632930435.555025] [modem0] state changed (registered -> connecting)
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.555694] [modem0/bearer45] launching connection with QMI port (cdc-wdm0) and data port (wwan0)
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.555772] [modem0/bearer45] defaulting to use static IP method
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.555814] [modem0/bearer45] running IPv6 connection setup
Sep 30 00:47:15 tici ModemManager[4279]: <debug> [1632930435.555852] [modem0/bearer45] setting default IP family to: IPv6
```

And output of mmcli -m 0:

  -----------------------------------
  Status   |                    lock: sim-pin2
           |          unlock retries: sim-pin (3), sim-puk (10), sim-pin2 (3), sim-puk2 (10)
           |                   state: connecting
           |             power state: on
           |             access tech: lte
           |          signal quality: 54% (cached)
  -----------------------------------


  -----------------------------------
  3GPP     |                    imei: xxx
           |           enabled locks: fixed-dialing
           |             operator id: 44010
           |           operator name: DOCOMO
           |            registration: home
  -----------------------------------

**Comment by andiradulescu** [comment]
Closing stalled PR. Feel free to reopen if still relevant.

**Pull request closed without merging**
