### PR TITLE
update bash scripts to #!/usr/bin/env bash

### PR DESCRIPTION
**Pull request by andiradulescu**
Mostly for macOS.

A good explaination [here](https://stackoverflow.com/a/58494728/639708).

Same thing for:
- openpilot https://github.com/commaai/openpilot/pull/33111
- panda https://github.com/commaai/panda/pull/1987

\* left `userspace` alone, for now, since it only runs on device

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can we setup pre-commit linting for this?

**Comment by andiradulescu** [comment]
We can setup pre-commit for this, but I'm starting to think to simply use:
```
#!/bin/bash
```
than
```
#!/usr/bin/env bash
```
and never:
```
#!/usr/bin/bash
```
More reading [here](https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my).

If we want pre-commit for scripts, we could also use:
- [shellcheck-py/shellcheck-py](https://github.com/shellcheck-py/shellcheck-py): runs [shellcheck](https://www.shellcheck.net/) on your scripts
- [openstack/bashate](https://github.com/openstack/bashate): code style enforcement for bash programs

(they don't check if you use `#!/bin/bash` or `#!/usr/bin/env bash` or `#!/usr/bin/bash`)

I kindly ask for more opinions: @adeebshihadeh  @maxime-desroches

---
FYI, this PR started from the fact that macOS doesn't have `bash` in `/usr/bin/` but only in `/bin`.

If a newer version of `bash` is installed on macOS, then `#!/usr/bin/env bash` will use that one instead of the one in `/bin`.

**Comment by adeebshihadeh** [comment]
Adding a bash linter sounds good, though make sure to keep the enforcing similar to our other linters. We generally only want to error on things that are clearly bad patterns or bugs.

**Comment by andiradulescu** [comment]
Will see what I can do about the bash linter.

Any preference towards `#!/usr/bin/env bash` vs `#!/bin/bash` ? Linted shebang?

**Comment by adeebshihadeh** [comment]
No preference, just want to enforce it's all the same with a linter.

**Comment by adeebshihadeh** [comment]
https://github.com/commaai/openpilot/issues/32761 is relevant here. We probably want to do some shebang linting.

**Comment by maxime-desroches** [comment]
I have not found an already existing linter that does this (especially for python3 vs python in the shebang). 
@andiradulescu Did you managed to find a linter that does that?

**Comment by andiradulescu** [comment]
No, I didn't. Maybe make our own linter(s)? That's what I want to do regarding the shebang.

**Pull request merged**
