### PR TITLE
ubuntu 23.10

### PR DESCRIPTION
**Pull request by adeebshihadeh**
prepping for the 20.04 -> 24.04 update

### CODE REVIEW

**Comment by andiradulescu** [comment]
Any help needed here?

**Comment by adeebshihadeh** [comment]
This is just some casual prep for 24.04. I'd be happy to merge ready-to-go PRs to further this prep, but won't have any time for reviews.

**Comment by andiradulescu** [comment]
I will take a look to see what else is needed and try to build the image and even flash it. I need 22.04 on my C3 to test something. So, I won’t submit a random PR just to waste your time.

If I submit a ready-to-go PR on this, how can I/you validate it without needing a review?

**Comment by adeebshihadeh** [comment]
I would approach it like this:
1. get >=22.04 Ubuntu working on a branch
2. open a PR for that just so we can see all the changes necessary
3. split out changes that we can start shipping now into their own PRs

#3 might or might now make sense depending on the changes. If nothing applies to 20.04 or makes sense to merge early, it'll still be valuable to have your PR up as a reference when I go to port too 24.04. To be clear, we're not gonna update the base version until 24.04 is out.

**Comment by andiradulescu** [comment]
Agree. Started working on this here https://github.com/andiradulescu/agnos-builder/tree/2204 will get back to you when I have a working image or if I hit something (and/or stop).

**Comment by andiradulescu** [comment]
I removed the bionic deps, since I was getting this error `GPG error: http://ports.ubuntu.com/ubuntu-ports bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32` and updated the deps from [here](https://github.com/commaai/agnos-builder/pull/183#issuecomment-1848929094.) to the appropiate 22.04 versions.

Now the next hop is that `qt5-default` has been removed on 22.04: https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg5902890.html / https://askubuntu.com/a/1337334/562170

There are two options going forward:
- make/build qt5 on 22.04
- upgrade to qt6 (although I think we'll have some blockers e.g. `mapbox-gl-native-qt`)

I suggest making qt5 work (https://askubuntu.com/questions/1404263/how-do-you-install-qt-on-ubuntu22-04) for this PR and upgrade to qt6 in a separate future PR.

I will continue with qt5. Let me know what you think.

**Comment by adeebshihadeh** [comment]
I think we have to stick with Qt5. Last time I looked into it, Qt6 didn’t have feature parity yet. If we build it ourselves, this is potentially something that can be merged early.

**Comment by adeebshihadeh** [comment]
@andiradulescu how's your 22.04 port going? I see Ubuntu has started pushing 24.04 builds. If you're interested in switching to that, I can put up a bounty to do 24.04.

http://www.cdimage.ubuntu.com/daily-live/current/

**Comment by andiradulescu** [comment]
@adeebshihadeh a bounty would help. I stopped when I ran out of free minutes (and space) on GitHub Codespaces and then I focused on something else.

If you put a bounty for 24.04, I will come back to this asap.

**Comment by adeebshihadeh** [comment]
Hmm, actually doesn't seem like they're pushing the ARM base images we need for 24.04, unless I'm missing something. I think the best we can do is 23.10 right now.

Let's do $500 for an AGNOS based on 23.10:
* full openpilot builds
* passes openpilot's `selfdrive/test/test_onroad.py`
* everything works except 1-2 very specific things (e.g. modem and audio output)

I think it'll be hard to get everything working reliably, which is why it's $500 and ok if a couple things don't work yet.

**Comment by andiradulescu** [comment]
@adeebshihadeh sounds good! I can resume immediately.

As for ARM base image I think this is the base image: https://cdimage.ubuntu.com/ubuntu-base/daily/current/**noble-base-arm64.tar.gz**

Is the bounty considered locked? If I fail or get blocked I will let you know.

**Comment by adeebshihadeh** [comment]
Oh cool, let's use that 24.04 image then. And yes, it's locked to you. Can you put up a PR so I can follow along :)

**Comment by andiradulescu** [comment]
https://github.com/commaai/agnos-builder/pull/188 thanks! ;)

**Comment by adeebshihadeh** [comment]
Closing this then, good luck!

**Pull request closed without merging**
