### PR TITLE
Update serviceproviders.xml

### PR DESCRIPTION
**Pull request by Ory0ne**
Added for the Britain part:
<name>Vodafone Smart Sim</name>
		<gsm>
			<network-id mcc="901" mnc="28"/>
			<apn value="ciot.vodafone.com">
				<plan type="prepaid"/>
				<usage type="internet"/>
				<username>vodafone</username>
				<password>vodafone</password>
			</apn>
		</gsm>

### CODE REVIEW

**Comment by Ory0ne** [comment]
https://v.vodafone.com/uk/help-and-support
The APN settings for the Vodafone Smart Sim

**Comment by pd0wm** [comment]
Have you verified updating the file on your own device makes LTE work?

**Comment by Ory0ne** [comment]
I'm trying to figure out how to do this ssh in to the comma, but I'm completely lost.
Is there any easy straightforward method to do that on Windows? I'm confused which private key I need how to set up the connection, do i need to connect local or it works through ssh.comma.ai...

**Comment by Ory0ne** [comment]
If you are unable to help, at least please let me know.
I will figure out how to change the file on the comma.
On the other hand, why the apn settings aren't more detailed in the os? If it would be no hassle would be necessary...

**Comment by Ory0ne** [comment]
Hi, I'm sorry, suddenly it's working. I don't know the reason why, since then nothing has changed as I know.
Shall I close the request?

**Comment by adeebshihadeh** [comment]
Yes, if it's working without this change, let's close this.

**Pull request closed without merging**
