### PR TITLE
[no merge] System build time improvements #2

### PR DESCRIPTION
**Pull request by robin-reckmann**
Continuation of https://github.com/commaai/agnos-builder/pull/278

### CODE REVIEW

**Comment by robin-reckmann** [comment]
- [x] Use apt-fast: 28m32s

**Comment by robin-reckmann** [comment]
- [x] Use apt-fast: 28m32s
- [x] System python and uv venv: 26m54s

**Comment by robin-reckmann** [comment]
- [x] Use apt-fast: 28m32s
- [x] System python and uv venv: 26m54s
- [x] Use only one `apt update`: 25m36s

**Comment by robin-reckmann** [comment]
- [x] Use apt-fast: 28m32s
- [x] System python and uv venv: 26m54s
- [x] Use only one `apt update`: 25m36s
- [x] Install uv python 3.12: 27m26s

**Comment by andiradulescu** [comment]
is this just for testing (in CI)? or you plan to merge it in the end?

**Comment by robin-reckmann** [comment]
It's just for testing the build runtimes in the CI. Any larger improvements are probably best to merge in via their own PR. So I will close this one at some point.

**Comment by andiradulescu** [comment]
Cool, asked just for triage/setting labels.

**Comment by robin-reckmann** [comment]
- [x] Use apt-fast: 28m32s
- [x] System python and uv venv: 26m54s ( -1m38s)
- [x] Use only one `apt update`: 25m36s ( -1m18s)
- [x] Install uv python 3.12: 27m26s ( +1m50s)
- [x] Build and install PyQt5 wheel: 24m14s ( -1m12s)

**Pull request closed without merging**
