### PR TITLE
Update Weston

### PR DESCRIPTION
**Pull request by andiradulescu**
@adeebshihadeh this is my proposal for https://github.com/commaai/agnos-builder/issues/16

This will update `weston` to the Linaro latest downstream (based on weston 8.0.0) for Ubuntu 20.04, used in Qualcomm Robotics RB5 Dev Kit / QRB5165. The manifest (and tag) used is [LU.UM.3.3.1.r1-25900-QRB5165.0](https://git.codelinaro.org/clo/le/wayland/weston/-/commits/LU.UM.3.3.1.r1-25900-QRB5165.0?ref_type=tags).

My proposal comes for a couple of reasons:
- using upstream weston (as it is) forces to use mesa/freedreno which has [sketchy](https://mesamatrix.net/#RusticlOpenCL) support for OpenCL
- using upstream weston with the adreno drivers would mean to put (the linaro) [patches](https://git.codelinaro.org/clo/le/wayland/weston/-/compare/8.0.0...LU.UM.3.3.1.r1-25900-QRB5165.0?from_project_id=22479&straight=false) on top of the upstream weston - which is the same thing as pulling the linaro downstream - if we want this, we could probably reduce the number of changes Linaro did (e.g. only import the [sdm_backend](https://git.codelinaro.org/clo/le/wayland/weston/-/commit/ee1cba18e6bdb04e48bbb7eacbb6f4a57994ec8a)), but there will be a lot of trial and error
- using weston 8 since Ubuntu 20.04 [uses](https://packages.ubuntu.com/focal/weston) weston 8

Please let me know what you think.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Bounty is locked! I'll have to take some time to review the approach and make sure it hits all the things we want to do.

**Comment by andiradulescu** [comment]
Thanks! Sure, take your time. I will putting this on hold for at least a couple of days.

Current progress is that all `compile-*.sh` steps compile fine, except `weston` which has some linking errors that need to be fixed next:
```
12.11 /usr/bin/ld: warning: liblog.so.0, needed by compositor/libexec_weston.so.0.0.0, not found (try using -rpath or -rpath-link)
12.11 /usr/bin/ld: compositor/libexec_weston.so.0.0.0: undefined reference to `__android_log_print'
12.11 /usr/bin/ld: libweston/libweston-8.so.0.0.0: undefined reference to `gbm_perform'
```

After `weston` compiles fine, I need to push the new version(s) of weston to my C3 and fix every problem one by one.

At the end, any private changes you have on the current `weston`, need to be copied over (as patches) to this PR.

**Comment by andiradulescu** [comment]
If you need it, the entire `LU.UM.3.3.1.r1-25900-QRB5165.0` Linaro release can be pulled with:
```
repo init --depth=1 --current-branch -u https://git.codelinaro.org/clo/le/le/manifest.git -b release -m LU.UM.3.3.1.r1-25900-QRB5165.0.xml --repo-url=https://git.codelinaro.org/clo/tools/repo.git --repo-branch=qc-stable
repo sync -j8 -c
```
This is from where I extracted manually all the compile phases. By hand.

**Comment by andiradulescu** [comment]
Last commits pack `weston` (and deps) in deb files, with applied patches.

Weston now loads fine, UI works except there is a lot of tearing because `backend-sdm` expects the kernel to support `atomic_modeset` for `drm`/`msm`/`adreno` drivers. From what I researched, it seems the support needed is from `4.19`. Our kernel is based on `4.9`.

What I'm currently trying to do, is finding/making a "fix" so that `backend-sdm` works without `atomic_modeset`. Since in weston 1.9.0 `compositor-sdm.c` doesn't need this.

Keep in mind that if you build from this branch, weston debs are not installed automatically (they are placed in `/tmp`, right now). I'm leaving this for the end.

**Comment by adeebshihadeh** [comment]
> * using weston 8 since Ubuntu 20.04 [uses](https://packages.ubuntu.com/focal/weston) weston 8

Which version does 24.04 use? Should we just go straight to that version?

**Comment by andiradulescu** [comment]
Ubuntu [24.04](https://packages.ubuntu.com/noble/weston) uses the latest Weston [13.0.0](https://wayland.freedesktop.org/releases.html). We can probably go straight to the latest.

The only issue right now is with the kernel drm to support atomic modesetting:
- either patch the current kernel (putting a newer drm on top)
- either update the kernel (to a version where it's easy/fast to apply all [changes](https://github.com/commaai/agnos-kernel-sdm845/compare/3666be0..c22355e) as patches - e.g. msm-4.19 or msm-5.4 from Linaro)
- find a fix (e.g. downgrade the `backend-sdm` to a version without atomic modesetting)

The next thing I'm trying is to patch the current kernel.

Mainlining the kernel will probably take more time than using a Linaro "downstream" msm kernel. But, there is some effort here https://github.com/robin-reckmann/comma3_mainline / https://github.com/commaai/agnos-builder/issues/16#issuecomment-1068000348 that needs to be tested/compared, since I have no idea if the "msm" specific stuff we need is already in mainline (and what isn't). My effort is towards using the sdm/drm adreno drivers (not freedreno).

**Comment by adeebshihadeh** [comment]
I'm hesitant to put more effort into the current kernel, since we'd like to go to mainline soon-ish. For mainline, the very latest or the 24.04 kernel are probably what we'd want to go with.

**Comment by andiradulescu** [comment]
> I'm hesitant to put more effort into the current kernel, since we'd like to go to mainline soon-ish. For mainline, the very latest or the 24.04 kernel are probably what we'd want to go with.

Just so you know, I am/was very hesitant in doing any work to make things work on anything except Ubuntu 24.04 / latest.

Indeed, I tried some easy fixes to see weston work 100% but spent little time actually doing this.

As for this branch, it has very little backward compatibility fixes (just some missing include files in kernel 4.9). They can be easily deleted. You can check the diff.

Next, I would see the following get done:
- clean/update old dependencies (including removal of armhf deps)
- mainline the kernel
- update weston 8 to weston 13

And this should be done, or close to done, in the Ubuntu 24.04 release window aka until April 25, 2024.

**Comment by andiradulescu** [comment]
The last conclusion of this PR on “old” 4.9 kernel is that it works but with lots of tearing, since there is no atomic modesetting which this version of weston with backend-sdm needs.

**Comment by andiradulescu** [comment]
Closing this PR, since changes in this PR, as they are, should not be needed anymore in mainline. More will be seen when weston is getting some work in mainline.

**Pull request closed without merging**
