### PR TITLE
bump edl

### PR DESCRIPTION
**Pull request by bongbui321**
This new update is less verbose when used with multiple commands in a row

### CODE REVIEW

**Comment by andiradulescu** [comment]
@bongbui321 with this new commit the terminal seems `hanged`, it may be flashing, but without the user knowing:

```khadas@Khadas:~/SSD/agnos-builder-2404$ ./flash_system.sh 
Flashing system...
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2023.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
```

Not sure I had the patience to leave it for 6 minutes, so I reverted to the previous version where I have this feedback:

```QCSparse - Sparse Format detected. Using unpacked image.
firehose - 
Writing to physical partition 0, sector 8712, sectors 2621440
Progress: |█████-----|  49.0% Write (Sector 0x139480 of 0x280000, 03m:33s left) 25.38 MB/s
```

**Comment by andiradulescu** [comment]
Separately, this is not an error, right?

```
firehose - Patch:
--------------------

firehose - bytearray(b'<?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<log value="INFO: Calling handler for patch" /></data><?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<response value="ACK" rawmode="false" /></data>')
firehose - Patch:
--------------------

firehose - bytearray(b'<?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<log value="INFO: Calling handler for patch" /></data><?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<response value="ACK" rawmode="false" /></data>')
firehose - Patch:
--------------------
...
```
(and repeats a lot of times)

**Comment by bongbui321** [comment]
@andiradulescu Not sure what you mean, but it works perfectly fine for me - Tested by running ./flash_bootloader, ./flash_system

**Comment by andiradulescu** [comment]
`./flash_system` just printed:
```
Flashing system...
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2023.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
```
Nothing else.

**Pull request merged**
