### PR TITLE
Build independent packages first

### PR DESCRIPTION
**Pull request by robin-reckmann**
Move package compilation to the beginning of the main dockerfile. This parts can now run in parallel to the main installation up until the compiled packages are installed.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
What does this improve? I generally find splitting up Dockerfiles to be pretty annoying since you have to manage each separately.

**Comment by robin-reckmann** [comment]
> What does this improve? I generally find splitting up Dockerfiles to be pretty annoying since you have to manage each separately.

Ok, so then I would move the compilers to the top of the existing Dockerfile.

**Comment by robin-reckmann** [comment]
Compile time test: https://github.com/commaai/agnos-builder/pull/359
min/max/avg : 8m46s / 9m02s / 8m54s

**Comment by andiradulescu** [comment]
Also shared this on Discord - I would create "agnos-base" from the tar.gz file instead of "ubuntu:24.04". God knows what differences might be (now or in the future) between them.

Besides this, LGTM!

**Comment by robin-reckmann** [comment]
I dont have a strong preference, which base to use. I compared the compiled binaries and they are identical. "agnos-base" is still using the tar.gz. Only the compiler is user docker ubuntu

**Pull request merged**
